# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_derive_avoidable_att <- function(df, colTypeED, colAttDischarge, colAttCategory, colArrivalMode, colsInvestigations, colsTreatments, clinicalCodeStandard, nthreads) {
    .Call('_ESAAvoidableAtt_cpp_derive_avoidable_att', PACKAGE = 'ESAAvoidableAtt', df, colTypeED, colAttDischarge, colAttCategory, colArrivalMode, colsInvestigations, colsTreatments, clinicalCodeStandard, nthreads)
}

cpp_get_max_threads <- function() {
    .Call('_ESAAvoidableAtt_cpp_get_max_threads', PACKAGE = 'ESAAvoidableAtt')
}

